In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd

In [2]:
file_path = "diabetes_012_ready_to_model.csv"

In [3]:
df_raw = pd.read_csv(file_path)

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229712 entries, 0 to 229711
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HighBP                229712 non-null  float64
 1   HighChol              229712 non-null  float64
 2   CholCheck             229712 non-null  float64
 3   Smoker                229712 non-null  float64
 4   Stroke                229712 non-null  float64
 5   HeartDiseaseorAttack  229712 non-null  float64
 6   PhysActivity          229712 non-null  float64
 7   Fruits                229712 non-null  float64
 8   Veggies               229712 non-null  float64
 9   HvyAlcoholConsump     229712 non-null  float64
 10  AnyHealthcare         229712 non-null  float64
 11  NoDocbcCost           229712 non-null  float64
 12  DiffWalk              229712 non-null  float64
 13  Sex                   229712 non-null  float64
 14  GenHlth               229712 non-null  float64
 15  Age                   229712 non-null  float64
 16  Education             229712 non-null  float64
 17  Income                229712 non-null  float64
 18  BMI                   229712 non-null  float64
 19  MentHlth              229712 non-null  float64
 20  PhysHlth              229712 non-null  float64
 21  Diabetes_012          229712 non-null  float64
dtypes: float64(22)
memory usage: 38.6 MB

1. reshape to meet the template

In [5]:
# extract the 8 features in the template
import json
template_json = "../tabular_template_building/tabular_feature_template.json" 

with open(template_json, "r") as f:
  templete = json.load(f)

In [6]:
t_features = templete["features"]
t_mask = templete["masks"]

t_features

['Age',
 'Sex',
 'BMI',
 'GenHlth',
 'HighBP',
 'DiffWalk',
 'HighChol',
 'HeartDiseaseorAttack']

In [7]:
df_8_features = df_raw.copy()

df_8_features = df_8_features[t_features]
df_8_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229712 entries, 0 to 229711
Data columns (total 8 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Age                   229712 non-null  float64
 1   Sex                   229712 non-null  float64
 2   BMI                   229712 non-null  float64
 3   GenHlth               229712 non-null  float64
 4   HighBP                229712 non-null  float64
 5   DiffWalk              229712 non-null  float64
 6   HighChol              229712 non-null  float64
 7   HeartDiseaseorAttack  229712 non-null  float64
dtypes: float64(8)
memory usage: 14.0 MB

In [8]:
for col in t_mask:
    df_8_features[col] = 1

df_8_features.head()

,Age,Sex,BMI,GenHlth,HighBP,DiffWalk,HighChol,HeartDiseaseorAttack,Age_mask,Sex_mask,BMI_mask,GenHlth_mask,HighBP_mask,DiffWalk_mask,HighChol_mask,HeartDiseaseorAttack_mask
0,9.0,0.0,40.0,5.0,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1
1,7.0,0.0,25.0,3.0,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1
2,9.0,0.0,28.0,5.0,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1
3,11.0,0.0,27.0,2.0,1.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1
4,11.0,0.0,24.0,2.0,1.0,0.0,1.0,0.0,1,1,1,1,1,1,1,1

In [9]:
df_label = df_raw["Diabetes_012"]
df_tabular_ready = pd.concat(
    [df_8_features, df_label], 
    axis=1
    )

df_tabular_ready.head()

,Age,Sex,BMI,GenHlth,HighBP,DiffWalk,HighChol,HeartDiseaseorAttack,Age_mask,Sex_mask,BMI_mask,GenHlth_mask,HighBP_mask,DiffWalk_mask,HighChol_mask,HeartDiseaseorAttack_mask,Diabetes_012
0,9.0,0.0,40.0,5.0,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0
1,7.0,0.0,25.0,3.0,0.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,0.0
2,9.0,0.0,28.0,5.0,1.0,1.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0
3,11.0,0.0,27.0,2.0,1.0,0.0,0.0,0.0,1,1,1,1,1,1,1,1,0.0
4,11.0,0.0,24.0,2.0,1.0,0.0,1.0,0.0,1,1,1,1,1,1,1,1,0.0

In [10]:
df_tabular_ready.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229712 entries, 0 to 229711
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Age                        229712 non-null  float64
 1   Sex                        229712 non-null  float64
 2   BMI                        229712 non-null  float64
 3   GenHlth                    229712 non-null  float64
 4   HighBP                     229712 non-null  float64
 5   DiffWalk                   229712 non-null  float64
 6   HighChol                   229712 non-null  float64
 7   HeartDiseaseorAttack       229712 non-null  float64
 8   Age_mask                   229712 non-null  int64
 9   Sex_mask                   229712 non-null  int64
 10  BMI_mask                   229712 non-null  int64
 11  GenHlth_mask               229712 non-null  int64
 12  HighBP_mask                229712 non-null  int64
 13  DiffWalk_mask              229712 non-null  int64
 14  HighChol_mask              229712 non-null  int64
 15  HeartDiseaseorAttack_mask  229712 non-null  int64
 16  Diabetes_012               229712 non-null  float64
dtypes: float64(9), int64(8)
memory usage: 29.8 MB

2. record feature_means, feature_vars and sample_count for global z-score norm in training

In [13]:
# drop the label column and any mask columns when computing feature stats
label_col = "Diabetes_012"
feature_cols = [c for c in df_tabular_ready.columns if not c.endswith("_mask") and c != label_col]

# compute per-feature mean and variance
feature_means = df_tabular_ready[feature_cols].mean().to_dict()
feature_vars = df_tabular_ready[feature_cols].var(ddof=0).to_dict()   # population variance

# build the JSON dict
site_stats = {
    "site_name": "tabular_1",
    "n_samples": int(len(df_tabular_ready)),
    "feature_means": feature_means,
    "feature_vars": feature_vars
}
site_stats

{'site_name': 'tabular_1',
 'n_samples': 229712,
 'feature_means': {'Age': 8.085981576931113,
  'Sex': 0.4391411854844327,
  'BMI': 28.68571080309257,
  'GenHlth': 2.6012049871142997,
  'HighBP': 0.4543776554990597,
  'DiffWalk': 0.1855584383924218,
  'HighChol': 0.441696559169743,
  'HeartDiseaseorAttack': 0.10321620115623041},
 'feature_vars': {'Age': 9.5726421687767,
  'Sex': 0.2462962046957598,
  'BMI': 46.064766216567136,
  'GenHlth': 1.1337465454985667,
  'HighBP': 0.24791860168223753,
  'DiffWalk': 0.15112650433378755,
  'HighChol': 0.24660070878735263,
  'HeartDiseaseorAttack': 0.09256261697510698}}

In [14]:
import json

with open("tabular_1_stats.json", "w", encoding="utf-8") as f:
    json.dump(site_stats, f, indent=2)

3. train-val-test split

In [25]:
# train-val-test split
# train + val vs test
tabular_train_val, tabular_test = train_test_split(
    df_tabular_ready, 
    test_size    = 0.2, 
    random_state = 42, 
    stratify = df_tabular_ready["Diabetes_012"]
    )

# train vs val
tabular_train, tabular_val = train_test_split(
    tabular_train_val, 
    test_size    = 0.25, 
    random_state = 42, 
    stratify = tabular_train_val["Diabetes_012"]
    )

In [26]:
# save to 3 CSVs
tabular_train.to_csv("diabetes_012_train.csv", index = False)
tabular_val.to_csv  ("diabetes_012_val.csv"  , index = False)
tabular_test.to_csv ("diabetes_012_test.csv" , index = False)

print("Train/Val/Test saved successfully.")

Train/Val/Test saved successfully.